export const FETCH_SESSION = "FETCH_SESSION";
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_SESSION_PENDING = "FETCH_SESSION_PENDING";
export const FETCH_SESSION_FULFILLED = "FETCH_SESSION_FULFILLED";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const LOGOUT_FULFILLED = "LOGOUT_FULFILLED";
export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_FULFILLED = "REGISTER_FULFILLED";
